### ISSUE TITLE
[question] init(protobuf: )

### ISSUE THREAD

**Issue by tannernelson** [apple/swift-protobuf-runtime#1]
This library looks awesome!

I was wondering if you could explain briefly how Swift structs are initialized with Data. There must be some magic going on there to make it dynamic. 

Thanks!

**Comment by tbkka** [comment]
It's not dynamic at all, actually.  To understand it more completely, you should probably start with Google's protobuf documentation:

   https://developers.google.com/protocol-buffers/

You can get some insight into how the Swift support works from the documentation for the protoc plugin:

  https://github.com/apple/swift-protobuf-plugin/blob/master/GENERATED_CODE.md#serialization-support

**Comment by tannernelson** [comment]
Oh I see, generated code. Makes sense. Thank you. :)
