### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by radex** [apple/swift-protobuf-runtime#3]
If the team is open to doing this, I'd be interested in adding a `.podspec` file to this repo. This would allow people to use this library via CocoaPods, which would make it more useful for iOS development today.

Even if no-one at Apple is interested in pushing and maintaining the library in CocoaPods trunk, a Podspec in the repo would allow people to fetch new versions of it like so:

~~~
pod 'swift-protobuf-runtime', git: 'git@github.com:apple/swift-protobuf-runtime.git'
~~~

**Comment by tbkka** [comment]
Sounds like a great idea!
Send us a Pull Request with the `.podspec` file.

**Comment by tbkka** [comment]
While you're at it, it would be great to add a short section to the README.md pointing out how to use this with CocoaPods.

**Comment by radex** [comment]
Fixed by #5.

**Comment by thomasvl** [comment]
@tbkka do you want to hold off on publishing the pod until things are fully stable?

**Comment by tbkka** [comment]
Personally, I would be happy if folks held off on publishing pods until things settle down.

**Comment by jcanizales** [comment]
People that really really want it can always point their Podfile to this GitHub repo. On the other hand, it's fair game for things versioned < 1.0 to be a moving ground.
